### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by Devesh-N**
I have added Dockerfile and it can automatically install all dependencies properly and with performance. It runs on localhost:3000. I have tested this and it is working!

### CODE REVIEW

**Comment by Devesh-N** [comment]
@ixahmedxi Please approve my merge request!

**Comment by matifali** [comment]
This would be a good addition. What about righting some docs on how to use the `Dockerfile`?

**Comment by matifali** [comment]
I get it, But docs should be better added in the same PR. your choice. :)

**Comment by Devesh-N** [comment]
@matifali I am a noob in this stuff I have no idea what I am doing. This is my first open-source contribution

**Comment by ixahmedxi** [comment]
While adding a Dockerfile is a great addition, for the current status of the project it is not a priority and will instead be added once we rely on the database, authentication, smtp server...etc

**Comment by Devesh-N** [comment]
> While adding a Dockerfile is a great addition, for the current status of the project it is not a priority and will instead be added once we rely on the database, authentication, smtp server...etc

@ixahmedxi Yes, but many users are facing issues, and if we give Dockerfile no possibility is there of any error. And also I would like to know if really only landing page is developed or more pages are there

**Pull request closed without merging**
